[project]
name = "bbox"
version = "1.0.0"
description = "Um script para criar uma bbox a partir de um ponto"
authors = [
    { name="Tharles de Sousa Andrade", email="irtharles@gmail.com" }
]
dependencies = [
    "pyproj",
    "shapely"
]

[project.scripts]
bbox = "bbox:main"